name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.1
  connectivity_plus: ^6.1.4
  retry: ^3.1.2
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  speech_to_text: ^7.0.0
  geocoding: ^3.0.0
  geolocator: ^13.0.4
  flutter_inappwebview: ^6.1.5
  flutter_map: ^8.1.1
  sqflite: ^2.4.2
  path: ^1.9.1
  flutter_svg: ^2.0.17
  home_widget: ^0.7.0+1
  get: ^4.6.6
  get_storage: ^2.0.3
  http: ^1.3.6
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/01d.svg
    - assets/svgs/01n.svg
    - assets/svgs/02d.svg
    - assets/svgs/02n.svg
    - assets/svgs/03d.svg
    - assets/svgs/03n.svg
    - assets/svgs/04d.svg
    - assets/svgs/04n.svg
    - assets/svgs/09n.svg
    - assets/svgs/09d.svg
    - assets/svgs/10d.svg
    - assets/svgs/10n.svg
    - assets/svgs/11d.svg
    - assets/svgs/11n.svg
    - assets/svgs/13d.svg
    - assets/svgs/13n.svg
    - assets/svgs/50d.svg
    - assets/svgs/50n.svg
    - assets/svgs/pop.svg
    - assets/svgs/sunset.svg
    - assets/svgs/sunrise.svg
    - assets/svgs/uvindex.svg
    - assets/svgs/openweather.svg
    - assets/svgs/AI.png
    - assets/svgs/map.png
    - assets/svgs/o.png
    - assets/svgs/detail.png
    - assets/svgs/setting.png
    - assets/svgs/wind.svg
    - assets/svgs/humidity.svg
    - assets/svgs/pressure.svg
    - assets/svgs/cloudiness.svg
    - assets/svgs/visibility.svg
    - assets/svgs/sea_level.svg
    - assets/weather_map.html
    - assets/images/
